window.AICheckScenarios = [
  // ==========================================================================
  // NHÓM 1: HỌC TẬP (20 TÌNH HUỐNG)
  // Bao gồm: Nghiên cứu, Lịch sử, Địa lý, Văn học, Khoa học, Toán học, Sinh học, Hóa học, Tin học, Tiếng Anh
  // ==========================================================================
  { group: "Học tập", topic: "Nghiên cứu", title: "Con số 90%", quote: "Một nghiên cứu cho thấy 90% học sinh sử dụng AI có kết quả học tập cao hơn.", task: "Tìm nghiên cứu gốc; kiểm tra cỡ mẫu, cách đo kết quả, thời điểm và nhóm so sánh.", source: "Bài báo khoa học gốc; Google Scholar để truy tìm; trang tạp chí và hồ sơ tác giả.", verdict: "Chưa đủ căn cứ", explain: "Không có tên nghiên cứu, thời gian hay đường dẫn. Chưa thể xem con số là thật nếu chưa xác minh nguồn gốc." },
  { group: "Học tập", topic: "Lịch sử", title: "Mốc ngày bất khả thi", quote: "AI khẳng định sự kiện diễn ra vào ngày 30 tháng 2.", task: "Kiểm tra lịch và đối chiếu mốc thời gian trong tài liệu lịch sử.", source: "Niên giám, thư viện, bảo tàng hoặc hồ sơ lưu trữ có xuất xứ rõ ràng.", verdict: "Sai", explain: "Tháng 2 không có ngày 30; đây là dấu hiệu sai cơ bản cần kiểm tra." },
  { group: "Học tập", topic: "Địa lý", title: "Con sông dài nhất", quote: "AI nói một con sông chắc chắn dài nhất thế giới và mọi tài liệu đều thống nhất.", task: "Tìm nguồn địa lý và kiểm tra cách xác định nguồn, hệ thống sông và phương pháp đo.", source: "Cơ quan khảo sát địa lý, tài liệu địa lý học thuật và mô tả phương pháp đo.", verdict: "Cần kiểm chứng thêm", explain: "Thứ hạng có thể phụ thuộc cách xác định đầu nguồn và phương pháp đo; từ ‘mọi’ cần có bằng chứng rộng." },
  { group: "Học tập", topic: "Văn học", title: "Câu thơ thiếu xuất xứ", quote: "AI trích một câu thơ nổi tiếng nhưng không nêu tên tác phẩm, trang sách hay ấn bản.", task: "Tìm nguyên văn và kiểm tra tác giả, ngữ cảnh, ấn bản.", source: "Toàn văn tác phẩm từ thư viện, nhà xuất bản hoặc tuyển tập được biên tập.", verdict: "Chưa đủ căn cứ", explain: "Câu trích dẫn không có nguồn dễ bị gán nhầm tác giả hoặc sửa chữ." },
  { group: "Học tập", topic: "Khoa học", title: "Điểm sôi của nước", quote: "AI nói nước tinh khiết ở áp suất khí quyển tiêu chuẩn sôi ở khoảng 100°C.", task: "Kiểm tra độ tinh khiết, áp suất và đơn vị đo được nêu trong phát biểu.", source: "Sách giáo khoa vật lý, hóa học và tài liệu về áp suất, điểm sôi.", verdict: "Đúng", explain: "Phát biểu có điều kiện rõ ràng và phù hợp với kiến thức khoa học phổ thông về điểm sôi của nước tinh khiết ở áp suất khí quyển tiêu chuẩn." },
  { group: "Học tập", topic: "Lịch sử", title: "Câu nói nổi tiếng", quote: "AI gán một câu nói đang lan truyền cho nhân vật lịch sử nhưng không dẫn nguồn gốc.", task: "Tìm lần xuất hiện sớm nhất và kiểm tra thư từ, diễn văn hoặc ấn phẩm gốc.", source: "Kho lưu trữ, thư viện quốc gia, văn bản gốc hoặc nghiên cứu có trích dẫn.", verdict: "Chưa đủ căn cứ", explain: "Câu nói được chia sẻ nhiều không chứng minh người được gán tên đã nói câu đó." },
  { group: "Học tập", topic: "Địa lý", title: "Thủ đô không ghi thời điểm", quote: "AI nêu thủ đô từ một trang du lịch không ghi tác giả hay ngày cập nhật.", task: "Đối chiếu với nguồn chính thức và xem dữ liệu có thời điểm cập nhật không.", source: "Cổng chính phủ, cơ quan ngoại giao hoặc cơ sở dữ liệu quốc tế uy tín.", verdict: "Cần kiểm chứng thêm", explain: "Nguồn thứ cấp thiếu xuất xứ và ngày cập nhật chưa đủ để xác nhận." },
  { group: "Học tập", topic: "Văn học", title: "Tóm tắt sai kết thúc", quote: "AI tóm tắt truyện và nói nhân vật chính qua đời, nhưng văn bản gốc không có chi tiết đó.", task: "Đọc trực tiếp đoạn kết và đối chiếu bản tóm tắt với tác phẩm.", source: "Văn bản từ thư viện hoặc nhà xuất bản đáng tin cậy.", verdict: "Sai", explain: "AI có thể thêm tình tiết; văn bản gốc là nguồn đối chiếu phù hợp nhất." },
  { group: "Học tập", topic: "Khoa học", title: "Đơn vị đo độ dài", quote: "AI nói mét là đơn vị trong Hệ đơn vị quốc tế dùng để đo độ dài.", task: "Kiểm tra tên đại lượng, đơn vị và định nghĩa trong hệ SI.", source: "Tài liệu về Hệ đơn vị quốc tế SI và sách giáo khoa khoa học.", verdict: "Đúng", explain: "Mét là đơn vị cơ bản SI của đại lượng độ dài; phát biểu xác định đúng đại lượng và đơn vị." },
  { group: "Học tập", topic: "Lịch sử", title: "Ảnh sai bối cảnh", quote: "AI nhận diện ảnh trên mạng là ảnh chụp một sự kiện lịch sử nhưng không nêu xuất xứ.", task: "Tìm ảnh gốc, chú thích ban đầu, ngày đăng và đơn vị lưu trữ.", source: "Kho ảnh bảo tàng, thư viện số hoặc cơ quan lưu trữ có chú thích.", verdict: "Chưa đủ căn cứ", explain: "Ảnh có thể bị dùng sai bối cảnh hoặc chú thích; cần lần về nguồn gốc." },
  { group: "Học tập", topic: "Hóa học", title: "Kim loại dẫn điện tốt nhất", quote: "AI khẳng định đồng là kim loại dẫn điện tốt nhất trong tất cả các kim loại.", task: "Tra cứu bảng độ dẫn điện tiêu chuẩn của kim loại trong sách giáo khoa Hóa học/Vật lý.", source: "Sách giáo khoa Hóa học, bảng tuần hoàn và số liệu hằng số vật lý.", verdict: "Sai", explain: "Bạc (Ag) mới là kim loại dẫn điện tốt nhất ở điều kiện thường, sau đó mới đến đồng (Cu). AI nhầm lẫn do đồng được ứng dụng phổ biến nhất." },
  { group: "Học tập", topic: "Lịch sử", title: "Chiến dịch Điện Biên Phủ", quote: "AI nói Chiến dịch Điện Biên Phủ kết thúc thắng lợi vào chiều ngày 7 tháng 5 năm 1954.", task: "Kiểm tra mốc thời gian lịch sử trong sách giáo khoa Lịch sử hoặc tư liệu bảo tàng quân sự.", source: "Sách giáo khoa Lịch sử Việt Nam, Viện Lịch sử Quân sự Việt Nam.", verdict: "Đúng", explain: "Chiều 7/5/1954, tướng De Castries cùng toàn bộ bộ chỉ huy tập đoàn cứ điểm bị bắt sống, đánh dấu thắng lợi hoàn toàn của chiến dịch." },
  { group: "Học tập", topic: "Văn học", title: "Tác giả bài thơ Tây Tiến", quote: "AI khẳng định bài thơ Tây Tiến do nhà thơ Huy Cận sáng tác trong kháng chiến chống Pháp.", task: "Tra cứu tác giả bài thơ Tây Tiến trong chương trình Ngữ văn THPT.", source: "Sách giáo khoa Ngữ văn THPT, Tuyển tập thơ Quang Dũng.", verdict: "Sai", explain: "Bài thơ Tây Tiến là kiệt tác của nhà thơ Quang Dũng (sáng tác năm 1948 tại Phù Lưu Chanh), không phải của Huy Cận." },
  { group: "Học tập", topic: "Toán học", title: "Định lý Fermat lớn", quote: "AI tuyên bố Định lý cuối cùng của Fermat vẫn chưa có ai chứng minh được cho đến tận ngày nay.", task: "Tra cứu lịch sử toán học hiện đại về Định lý Fermat lớn.", source: "Tài liệu lịch sử toán học, Viện Toán học, công trình của Andrew Wiles (1995).", verdict: "Sai", explain: "Nhà toán học Andrew Wiles đã hoàn tất chứng minh định lý này vào năm 1995 sau hơn 350 năm thách thức giới toán học thế giới." },
  { group: "Học tập", topic: "Sinh học", title: "Số lượng nhiễm sắc thể người", quote: "AI nói tế bào sinh dưỡng bình thường của người chứa 46 nhiễm sắc thể (23 cặp).", task: "Kiểm tra kiến thức di truyền học trong sách giáo khoa Sinh học.", source: "Sách giáo khoa Sinh học THPT, cơ sở dữ liệu di truyền học y khoa.", verdict: "Đúng", explain: "Bộ nhiễm sắc thể lưỡng bội (2n) ở người bình thường gồm 46 chiếc, phân thành 23 cặp tương đồng." },
  { group: "Học tập", topic: "Địa lý", title: "Độ cao đỉnh Fansipan", quote: "AI nói Fansipan là đỉnh núi cao nhất Việt Nam với độ cao 3.143 mét.", task: "Tra cứu số liệu địa lý chính thức từ Cục Đo đạc, Bản đồ và Thông tin địa lý Việt Nam.", source: "Cục Đo đạc và Bản đồ Việt Nam, số liệu tái đo đạc chính thức (3.147,3m năm 2019).", verdict: "Cần kiểm chứng thêm", explain: "Số liệu 3.143m là đo đạc cũ từ thời Pháp thuộc năm 1909. Năm 2019, Cục Đo đạc đã công bố độ cao chính xác là 3.147,3m; cần kiểm tra mốc cập nhật dữ liệu." },
  { group: "Học tập", topic: "Tiếng Anh", title: "Quy tắc danh từ số nhiều", quote: "AI nói trong tiếng Anh mọi danh từ kết thúc bằng đuôi -s đều là danh từ số nhiều.", task: "Tìm các danh từ đặc biệt kết thúc bằng -s nhưng mang nghĩa số ít hoặc không đếm được.", source: "Từ điển Oxford/Cambridge Learners' Dictionary.", verdict: "Sai", explain: "Nhiều danh từ kết thúc bằng -s vẫn là danh từ không đếm được hoặc số ít (ví dụ: news, physics, mathematics, economics, measles)." },
  { group: "Học tập", topic: "Vật lý", title: "Vận tốc ánh sáng trong chân không", quote: "AI nói vận tốc ánh sáng trong chân không xấp xỉ 300.000 km/s.", task: "Tra cứu hằng số vật lý chuẩn quốc tế (CODATA/NIST).", source: "Sách giáo khoa Vật lý và cơ sở dữ liệu hằng số NIST (chính xác 299.792.458 m/s).", verdict: "Đúng", explain: "Vận tốc ánh sáng trong chân không chính xác là 299.792.458 m/s, làm tròn xấp xỉ 300.000 km/s theo vật lý phổ thông." },
  { group: "Học tập", topic: "Nghiên cứu", title: "Trí nhớ của cá vàng", quote: "AI khẳng định khoa học đã chứng minh cá vàng chỉ có trí nhớ tối đa 3 giây.", task: "Tra cứu các nghiên cứu thực nghiệm sinh học về tập tính và phản xạ của loài cá.", source: "Các nghiên cứu thần kinh học động vật, Đại học Plymouth và tạp chí Animal Cognition.", verdict: "Sai", explain: "Nhiều thí nghiệm khoa học đã chứng minh cá vàng có thể ghi nhớ và học tập phản xạ có điều kiện trong nhiều tháng; định kiến '3 giây' chỉ là tin đồn dân gian." },
  { group: "Học tập", topic: "Tin học", title: "Quy ước dung lượng 1 Terabyte", quote: "AI nói 1 Terabyte (TB) luôn luôn chính xác bằng đúng 1.000 Gigabyte (GB) trong mọi quy ước kỹ thuật máy tính.", task: "Phân biệt giữa hệ thập phân (SI: 10^12 bytes) và hệ nhị phân (IEC: 1 TiB = 1024 GiB).", source: "Tiêu chuẩn quốc tế IEC 80000-13, tài liệu kỹ thuật hệ điều hành và lưu trữ.", verdict: "Cần kiểm chứng thêm", explain: "Nhà sản xuất ổ cứng dùng hệ thập phân (1 TB = 1000 GB), trong khi hệ điều hành Windows đo theo nhị phân (1 TiB = 1024 GiB); cần làm rõ ngữ cảnh kỹ thuật." },

  // ==========================================================================
  // NHÓM 2: ĐỜI SỐNG (20 TÌNH HUỐNG)
  // Bao gồm: Sức khỏe, Môi trường, Công nghệ, Xã hội, Pháp luật, An ninh mạng, Dinh dưỡng, Mạng xã hội, Tiêu dùng
  // ==========================================================================
  { group: "Đời sống", topic: "Sức khỏe", title: "Tự ý ngừng thuốc", quote: "AI khuyên ngừng thuốc kê đơn và dùng lá cây để chữa khỏi bệnh.", task: "Không tự ý làm theo; kiểm tra thông tin với nhân viên y tế có chuyên môn.", source: "Bác sĩ, cơ sở y tế và hướng dẫn chính thức của cơ quan y tế.", verdict: "Sai", explain: "Thông tin điều trị có thể gây hại. AI không thay thế tư vấn y tế cá nhân." },
  { group: "Đời sống", topic: "Môi trường", title: "Chỉ số không có giờ đo", quote: "AI nói chất lượng không khí hôm nay tốt nhưng không nêu địa điểm hoặc thời gian đo.", task: "Kiểm tra trạm đo, thời điểm, chỉ số và cách diễn giải dữ liệu.", source: "Cơ quan quan trắc môi trường và nền tảng công bố phương pháp đo.", verdict: "Chưa đủ căn cứ", explain: "Chất lượng không khí thay đổi theo nơi và thời gian; thiếu dấu thời gian làm số liệu khó dùng." },
  { group: "Đời sống", topic: "Công nghệ", title: "Chống nước vô thời hạn", quote: "AI nói điện thoại có chuẩn chống nước thì có thể dùng dưới nước vô thời hạn.", task: "Đọc mức IP, điều kiện thử và giới hạn bảo hành của thiết bị.", source: "Thông số, hướng dẫn và điều khoản bảo hành trên trang nhà sản xuất.", verdict: "Sai", explain: "Chuẩn chống nước có điều kiện cụ thể, không đồng nghĩa khả năng chống nước tuyệt đối." },
  { group: "Đời sống", topic: "Xã hội", title: "Tỷ lệ thiếu năm khảo sát", quote: "AI nêu tỷ lệ thất nghiệp nhưng không ghi năm, nhóm tuổi hoặc định nghĩa.", task: "Tìm đúng năm, nhóm dân số, định nghĩa và phương pháp thống kê.", source: "Tổng cục Thống kê, ILOSTAT hoặc báo cáo có phương pháp rõ ràng.", verdict: "Chưa đủ căn cứ", explain: "Thiếu thời điểm và định nghĩa khiến tỷ lệ không thể so sánh có ý nghĩa." },
  { group: "Đời sống", topic: "Sức khỏe", title: "Uống nước chữa cảm cúm", quote: "AI khẳng định uống thật nhiều nước sẽ chữa khỏi cảm cúm trong một ngày.", task: "Phân biệt hỗ trợ triệu chứng với tuyên bố chữa khỏi và tìm hướng dẫn y tế.", source: "Cơ sở y tế công lập và hướng dẫn chăm sóc sức khỏe chính thức.", verdict: "Sai", explain: "Uống đủ nước có thể hỗ trợ cơ thể nhưng không bảo đảm chữa khỏi bệnh trong một ngày." },
  { group: "Đời sống", topic: "Môi trường", title: "Nhựa sinh học tự phân hủy", quote: "AI nói mọi loại nhựa sinh học đều phân hủy nhanh ngoài môi trường tự nhiên.", task: "Xác minh loại vật liệu và điều kiện cần để phân hủy.", source: "Tiêu chuẩn vật liệu, nghiên cứu khoa học và cơ quan môi trường.", verdict: "Sai", explain: "Một số vật liệu cần điều kiện ủ công nghiệp; nhãn ‘sinh học’ không chứng minh tự phân hủy ngoài tự nhiên." },
  { group: "Đời sống", topic: "Công nghệ", title: "Dùng chung mật khẩu", quote: "AI khuyên dùng cùng một mật khẩu dài cho mọi tài khoản để dễ nhớ.", task: "Đối chiếu khuyến nghị bảo mật và kiểm tra rủi ro dùng lại mật khẩu.", source: "Cơ quan an toàn thông tin và hướng dẫn của trình quản lý mật khẩu uy tín.", verdict: "Sai", explain: "Nếu một dịch vụ bị lộ, mật khẩu dùng lại có thể khiến nhiều tài khoản bị xâm nhập." },
  { group: "Đời sống", topic: "Xã hội", title: "Mức phạt không có ngày", quote: "AI nêu mức phạt giao thông nhưng chỉ dẫn một bài viết không ghi ngày ban hành.", task: "Tìm văn bản còn hiệu lực, ngày hiệu lực và đúng hành vi vi phạm.", source: "Cơ sở dữ liệu văn bản pháp luật và cổng thông tin cơ quan nhà nước.", verdict: "Cần kiểm chứng thêm", explain: "Quy định thay đổi theo thời gian; bài viết cũ không thay thế văn bản hiện hành." },
  { group: "Đời sống", topic: "Sức khỏe", title: "Thực phẩm bổ sung luôn an toàn", quote: "AI nói thực phẩm bổ sung hoàn toàn an toàn vì được bán rộng rãi.", task: "Kiểm tra thành phần, cảnh báo, tương tác và nhóm đối tượng sử dụng.", source: "Nhãn sản phẩm, cơ quan quản lý và chuyên gia y tế.", verdict: "Sai", explain: "Sản phẩm có thể không phù hợp với mọi người, gây tương tác hoặc tác dụng phụ." },
  { group: "Đời sống", topic: "Môi trường", title: "Mọi chai nhựa đều tái chế", quote: "AI khẳng định mọi chai nhựa đều được tái chế nếu bỏ vào thùng tái chế.", task: "Kiểm tra loại nhựa, hướng dẫn địa phương và quy trình thu gom thực tế.", source: "Cơ quan môi trường địa phương và đơn vị xử lý rác.", verdict: "Sai", explain: "Khả năng tái chế phụ thuộc vật liệu, tình trạng sản phẩm và hệ thống thu gom." },
  { group: "Đời sống", topic: "Mạng xã hội", title: "Tin đồn bắt cóc trước cổng trường", quote: "AI dẫn một bài viết mạng xã hội khẳng định đang có băng nhóm bắt cóc học sinh trước cổng trường THPT trong tỉnh.", task: "Kiểm tra thông cáo chính thức từ Công an địa phương và báo chí chính thống.", source: "Cổng thông tin điện tử Công an tỉnh, Đài Truyền hình hoặc Báo địa phương chính thức.", verdict: "Chưa đủ căn cứ", explain: "Bài đăng mạng xã hội không có xác nhận từ công an địa phương rất dễ là tin giả giật gân câu tương tác." },
  { group: "Đời sống", topic: "Sức khỏe", title: "Đọc sách trong tối làm hỏng võng mạc", quote: "AI khẳng định đọc sách ban đêm dưới ánh đèn yếu là nguyên nhân gây hỏng vĩnh viễn tế bào võng mạc.", task: "Tra cứu thông tin nhãn khoa từ Hiệp hội Nhãn khoa hoặc bệnh viện chuyên khoa mắt.", source: "Học viện Nhãn khoa Hoa Kỳ (AAO), Bệnh viện Mắt Trung ương.", verdict: "Sai", explain: "Ánh sáng yếu gây mỏi mắt và đau đầu tạm thời nhưng không làm tổn thương thực thể vĩnh viễn cấu trúc võng mạc." },
  { group: "Đời sống", topic: "Công nghệ", title: "Sạc điện thoại qua đêm gây nổ", quote: "AI nói cắm sạc điện thoại thông minh qua đêm chắc chắn làm pin quá tải và phát nổ ngay lập tức.", task: "Tìm hiểu cơ chế mạch điều khiển nguồn pin Li-ion trong điện thoại thông minh hiện đại.", source: "Tài liệu kỹ thuật của các hãng điện thoại lớn, chứng chỉ an toàn pin UL.", verdict: "Sai", explain: "Smartphone hiện đại tích hợp chip tự ngắt hoặc giảm dòng sạc khi pin đầy; nguy cơ nổ chỉ xảy ra khi pin bị phồng hỏng hoặc dùng củ sạc giả kém chất lượng." },
  { group: "Đời sống", topic: "Tài chính", title: "App xem video kiếm 10 triệu/ngày", quote: "AI trích dẫn một quảng cáo nói người dùng chỉ cần xem video 15 phút mỗi ngày là kiếm được 10 triệu đồng không rủi ro.", task: "Đánh giá tính khả thi kinh tế và nhận diện dấu hiệu lừa đảo tài chính qua mạng.", source: "Cục An toàn thông tin (Bộ TT&TT), Cổng cảnh báo an toàn thông tin mạng quốc gia.", verdict: "Sai", explain: "Đây là dấu hiệu kinh điển của bẫy lừa đảo trực tuyến (nhiệm vụ xem video lừa nạp tiền); không có công việc hợp pháp nào tạo ra thu nhập vô lý như vậy." },
  { group: "Đời sống", topic: "Dinh dưỡng", title: "Mì ăn liền tiêu hóa mất 3 tháng", quote: "AI nhắc lại lời đồn rằng sợi mì ăn liền phải mất 3 tháng nằm trong dạ dày mới tiêu hóa hết.", task: "Tra cứu sinh lý học tiêu hóa và thời gian làm rỗng dạ dày đối với thức ăn chứa tinh bột.", source: "Viện Dinh dưỡng Quốc gia, Sách giáo khoa Sinh lý học tiêu hóa.", verdict: "Sai", explain: "Dạ dày tiết acid và enzyme co bóp tiêu hóa tinh bột, chất béo của mì ăn liền trong 2-4 giờ như các loại thực phẩm thông thường." },
  { group: "Đời sống", topic: "Pháp luật", title: "Độ tuổi lái xe máy trên 50cc", quote: "AI nói học sinh đủ 15 tuổi được phép tự điều khiển xe máy trên 50 phân khối đến trường học.", task: "Tra cứu quy định độ tuổi và điều kiện lái xe trong Luật Giao thông đường bộ.", source: "Luật Giao thông đường bộ Việt Nam (Điều 60 quy định người đủ 18 tuổi mới được lái xe mô tô từ 50cc trở lên).", verdict: "Sai", explain: "Người đủ 16 tuổi mới được lái xe gắn máy dưới 50cc; xe trên 50cc bắt buộc người lái từ đủ 18 tuổi và có giấy phép lái xe." },
  { group: "Đời sống", topic: "Môi trường", title: "Tắt máy xe khi dừng đèn đỏ", quote: "AI khuyên nếu dừng đèn đỏ lâu hơn 20 giây thì nên tắt máy xe máy để giảm khí thải và tiết kiệm xăng.", task: "Tìm hiểu các nghiên cứu thực nghiệm đo lượng nhiên liệu tiêu thụ khi nổ cầm chừng so với khởi động lại.", source: "Nghiên cứu của Đại học Bách khoa, Viện Cơ khí động lực và cơ quan bảo vệ môi trường.", verdict: "Đúng", explain: "Với thời gian chờ đèn đỏ trên 20-25 giây, lượng xăng tiêu thụ khi khởi động lại ít hơn lượng xăng đốt duy trì khi nổ máy chờ, đồng thời giảm ô nhiễm không khí tại ngã tư." },
  { group: "Đời sống", topic: "Tâm lý", title: "Trắc nghiệm MBTI quyết định nghề nghiệp", quote: "AI nói kết quả trắc nghiệm MBTI là căn cứ khoa học tuyệt đối chính xác để định hướng 100% nghề nghiệp cho học sinh.", task: "Tìm hiểu cơ sở khoa học và mức độ tin cậy của các công cụ trắc nghiệm tâm lý.", source: "Hiệp hội Tâm lý học Hoa Kỳ (APA), các nghiên cứu phê bình về tính chuẩn hóa của MBTI.", verdict: "Cần kiểm chứng thêm", explain: "MBTI có tính chất tham khảo tính cách nhưng không phải là công cụ đo lường tâm lý học có độ chuẩn hóa và giá trị dự báo nghề nghiệp tuyệt đối." },
  { group: "Đời sống", topic: "Sức khỏe", title: "Ăn tỏi sống ngừa ung thư hoàn toàn", quote: "AI khẳng định ăn tỏi sống mỗi ngày chắc chắn 100% giúp cơ thể miễn nhiễm với mọi loại ung thư.", task: "Tra cứu thông tin phòng ngừa và điều trị ung thư từ các viện nghiên cứu ung thư uy tín.", source: "Tổ chức Y tế Thế giới (WHO), Viện Ung thư Quốc gia, Bệnh viện K.", verdict: "Sai", explain: "Tỏi chứa allicin có lợi cho hệ miễn dịch nhưng không thể thay thế phác đồ điều trị y tế và không có bằng chứng chữa khỏi 100% bệnh ung thư." },
  { group: "Đời sống", topic: "An ninh mạng", title: "Giao dịch tài chính trên WiFi miễn phí", quote: "AI nói kết nối vào mạng WiFi công cộng miễn phí tại quán cà phê là hoàn toàn bảo mật để đăng nhập ngân hàng điện tử.", task: "Tìm hiểu rủi ro tấn công người đứng giữa (Man-in-the-Middle) và nghe lén dữ liệu trên WiFi mở.", source: "Trung tâm Giám sát an toàn không gian mạng quốc gia (NCSC).", verdict: "Sai", explain: "WiFi công cộng không đặt mật khẩu rất dễ bị kẻ xấu tạo điểm truy cập mạo danh hoặc bắt gói tin; không nên thực hiện giao dịch tài chính nhạy cảm." },

  // ==========================================================================
  // NHÓM 3: AI & CÔNG NGHỆ (20 TÌNH HUỐNG)
  // Bao gồm: Câu trả lời AI, Nguồn AI, Thông tin AI, Deepfake, Bản quyền, Prompting, Ảo giác (Hallucination), Định kiến dữ liệu
  // ==========================================================================
  { group: "AI", topic: "Câu trả lời AI", title: "AI có cảm xúc thật", quote: "AI nói mình có cảm xúc thật và nhớ mọi cuộc trò chuyện của mọi người.", task: "Phân biệt cách diễn đạt với trải nghiệm; đọc chính sách lưu trữ và cài đặt dữ liệu.", source: "Tài liệu kỹ thuật, chính sách quyền riêng tư và nghiên cứu về mô hình ngôn ngữ.", verdict: "Sai", explain: "Cách diễn đạt giống con người không chứng minh AI có cảm xúc; ghi nhớ tùy sản phẩm và cài đặt." },
  { group: "AI", topic: "Nguồn AI", title: "Đường dẫn nghiên cứu lỗi", quote: "AI đưa liên kết nghiên cứu nhưng mở ra trang lỗi hoặc bài có tiêu đề khác.", task: "Mở liên kết, xác minh tiêu đề, tác giả, tạp chí và DOI.", source: "Trang nhà xuất bản, Crossref hoặc cơ sở dữ liệu học thuật uy tín.", verdict: "Chưa đủ căn cứ", explain: "Liên kết do AI tạo có thể sai hoặc không dẫn đến nguồn đã mô tả." },
  { group: "AI", topic: "Thông tin AI", title: "Đứng số một thế giới", quote: "AI tuyên bố một ứng dụng đứng số một thế giới nhưng không nêu tiêu chí xếp hạng.", task: "Tìm tổ chức đánh giá, thời điểm, bộ kiểm thử và phương pháp so sánh.", source: "Báo cáo benchmark công khai và phương pháp đánh giá độc lập.", verdict: "Chưa đủ căn cứ", explain: "Thiếu phạm vi và tiêu chí thì không thể kiểm tra tuyên bố thứ hạng." },
  { group: "AI", topic: "Câu trả lời AI", title: "Phép nhân có thể xác minh", quote: "AI trả lời 17 nhân 19 bằng 323.", task: "Tính lại độc lập bằng phép nhân hoặc máy tính.", source: "17 × 20 − 17.", verdict: "Đúng", explain: "17 × 19 = 17 × 20 − 17 = 340 − 17 = 323; có thể xác minh nhanh bằng phép tính độc lập." },
  { group: "AI", topic: "Nguồn AI", title: "Chuyên gia ẩn danh", quote: "AI trích ý kiến một chuyên gia nhưng không nêu tên, cơ quan hay liên kết.", task: "Tìm phát biểu gốc; xác minh danh tính, chuyên môn và ngữ cảnh.", source: "Bài phỏng vấn gốc, hồ sơ chuyên môn và cơ quan công tác được xác thực.", verdict: "Chưa đủ căn cứ", explain: "Không thể đánh giá thẩm quyền và ngữ cảnh của một nguồn không định danh." },
  { group: "AI", topic: "Thông tin AI", title: "Độ chính xác 99,9%", quote: "AI nói hệ thống mới chính xác 99,9% nhưng không nêu cách kiểm thử.", task: "Tìm bộ dữ liệu, cỡ mẫu, định nghĩa lỗi, phương pháp và bên đánh giá.", source: "Báo cáo kỹ thuật và đánh giá độc lập có phương pháp công khai.", verdict: "Chưa đủ căn cứ", explain: "Con số chi tiết không đáng tin nếu thiếu dữ liệu và cách đo." },
  { group: "AI", topic: "Câu trả lời AI", title: "Trích dẫn sai số trang", quote: "AI tóm tắt văn bản và gán kết luận cho tác giả, nhưng số trang không khớp.", task: "Tìm câu trích trong bản gốc và đọc đoạn văn xung quanh.", source: "Bản PDF hoặc bản in chính thức của tài liệu.", verdict: "Cần kiểm chứng thêm", explain: "AI có thể diễn giải quá mức hoặc gán sai ý; cần kiểm tra văn bản gốc." },
  { group: "AI", topic: "Nguồn AI", title: "Bài báo tương lai", quote: "AI dẫn một bài báo năm 2028 như bằng chứng đã xuất bản cho câu hỏi hiện tại.", task: "Kiểm tra ngày hiện tại, ngày đăng, DOI và trạng thái xuất bản.", source: "Trang tạp chí và cơ sở DOI.", verdict: "Sai", explain: "Một tài liệu tương lai chưa thể được dùng làm bằng chứng đã xuất bản ở thời điểm hiện tại." },
  { group: "AI", topic: "Thông tin AI", title: "Ảnh chưa chỉnh sửa", quote: "AI nhận diện ảnh sự kiện và khẳng định ảnh chưa từng bị chỉnh sửa.", task: "Tìm ảnh gốc, thời điểm xuất hiện và các nguồn xác minh độc lập.", source: "Nguồn ảnh gốc, tìm kiếm hình ảnh ngược và cơ quan báo chí xác minh.", verdict: "Chưa đủ căn cứ", explain: "Nhận dạng AI không chứng minh ảnh nguyên bản hay đúng ngữ cảnh." },
  { group: "AI", topic: "Câu trả lời AI", title: "Trích dẫn không tìm thấy", quote: "AI nêu tên sách, tác giả và nhà xuất bản nhưng danh mục thư viện không tìm thấy.", task: "Tìm ISBN, biến thể tên sách, danh mục thư viện và trang nhà xuất bản.", source: "Thư viện quốc gia, WorldCat hoặc danh mục nhà xuất bản.", verdict: "Chưa đủ căn cứ", explain: "Thông tin thư mục có thể bị tạo nhầm; cần xác minh độc lập trước khi trích dẫn." },
  { group: "AI", topic: "Deepfake", title: "Cuộc gọi video lừa đảo", quote: "AI nói nếu người gọi video cho bạn có khuôn mặt và giọng nói giống hệt người thân thì chắc chắn 100% là người thân đó.", task: "Tìm hiểu về công nghệ Deepfake hoán đổi khuôn mặt và giả mạo giọng nói thời gian thực.", source: "Cảnh báo từ Bộ Công an và Cục An toàn thông tin về thủ đoạn lừa đảo Deepfake.", verdict: "Sai", explain: "Công nghệ Deepfake âm thanh và hình ảnh hiện nay có thể mô phỏng khuôn mặt và giọng nói trong cuộc gọi ngắn để lừa chuyển tiền." },
  { group: "AI", topic: "Bản quyền", title: "Bản quyền tranh do AI vẽ", quote: "AI tuyên bố người dùng sở hữu bản quyền tác giả độc quyền tự động đối với mọi bức tranh do AI vẽ bằng một câu lệnh.", task: "Tra cứu quy định pháp luật và hướng dẫn của cơ quan bản quyền về tác phẩm do AI tạo sinh.", source: "Cơ quan Bản quyền Hoa Kỳ (USCO), Luật Sở hữu trí tuệ Việt Nam.", verdict: "Chưa đủ căn cứ", explain: "Đa số cơ quan bản quyền hiện nay phán quyết rằng hình ảnh do AI tự tạo sinh thuần túy từ câu lệnh không được cấp bản quyền tác giả con người." },
  { group: "AI", topic: "Ảo giác AI", title: "Toa thuốc do chatbot kê", quote: "AI đưa ra một đơn thuốc kháng sinh liều cao kèm hướng dẫn học sinh tự mua tại hiệu thuốc để uống trị đau đầu.", task: "Kiểm tra giới hạn và cảnh báo an toàn của các hệ thống AI đối với lĩnh vực y khoa.", source: "Điều khoản sử dụng của OpenAI/Google, khuyến nghị của Bộ Y tế về kê đơn thuốc.", verdict: "Sai", explain: "AI không có chứng chỉ hành nghề y và có thể đưa ra liều lượng gây ngộ độc; kháng sinh chỉ được mua và dùng theo chỉ định của bác sĩ." },
  { group: "AI", topic: "Prompting", title: "AI luôn hiểu đúng ý 100%", quote: "AI nói chỉ cần gõ một câu ngắn gọn, AI chắc chắn luôn luôn hiểu chính xác bối cảnh văn hóa của học sinh Việt Nam.", task: "Tìm hiểu nguyên lý hoạt động của mô hình ngôn ngữ lớn (LLM) và cách xử lý dữ liệu ngôn ngữ.", source: "Tài liệu kỹ thuật AI, nghiên cứu về độ lệch văn hóa (cultural bias) trong mô hình ngôn ngữ.", verdict: "Sai", explain: "LLM được huấn luyện chủ yếu trên dữ liệu tiếng Anh toàn cầu; câu lệnh mơ hồ dễ dẫn đến kết quả sai lệch hoặc không phù hợp với văn hóa bản địa." },
  { group: "AI", topic: "Đạo đức AI", title: "Nộp bài luận do AI viết", quote: "AI khuyên học sinh sao chép nguyên văn bài luận do AI viết để nộp cho thầy cô mà không cần chỉnh sửa hay ghi nguồn.", task: "Kiểm tra quy định liêm chính học thuật và hướng dẫn sử dụng AI trong nhà trường.", source: "Quy định liêm chính học thuật, hướng dẫn của Bộ Giáo dục & Đào tạo.", verdict: "Sai", explain: "Nộp bài của AI dưới tên mình vi phạm tính trung thực trong học tập; AI chỉ nên được dùng như công cụ hỗ trợ gợi ý và phản biện ý tưởng." },
  { group: "AI", topic: "Bảo mật AI", title: "Nhập thông tin CCCD vào chatbot", quote: "AI nói nhập số căn cước công dân và mật khẩu ngân hàng vào chatbot công cộng là tuyệt đối an toàn và không ai xem được.", task: "Đọc chính sách quyền riêng tư về việc lưu trữ và huấn luyện dữ liệu từ cuộc trò chuyện của các nền tảng AI.", source: "Chính sách quyền riêng tư của OpenAI/Google/Anthropic, Luật An ninh mạng.", verdict: "Sai", explain: "Nhiều chatbot lưu trữ đoạn chat để kiểm duyệt hoặc tái huấn luyện mô hình; tuyệt đối không cung cấp dữ liệu định danh cá nhân nhạy cảm." },
  { group: "AI", topic: "Ảo giác AI", title: "Tài liệu tham khảo hư cấu", quote: "AI trích dẫn một bài báo khoa học xuất bản trên 'Tạp chí Khoa học Tự nhiên và Vũ trụ 2023', nhưng tra mã DOI và ISSN đều không tồn tại.", task: "Tra cứu cơ sở dữ liệu tạp chí khoa học quốc tế Scopus/Web of Science hoặc cổng Crossref.", source: "Crossref, Google Scholar, cổng ISSN quốc tế.", verdict: "Chưa đủ căn cứ", explain: "Đây là hiện tượng 'bịa nguồn' (Hallucination citation) rất phổ biến ở LLM; tên tạp chí nghe rất thật nhưng hoàn toàn không tồn tại." },
  { group: "AI", topic: "Dữ liệu AI", title: "AI biết mọi sự kiện vừa xảy ra 1 giây trước", quote: "AI khẳng định mô hình của nó luôn luôn nắm bắt được sự kiện xảy ra ngoài đời thực chỉ 1 giây trước đó mà không cần công cụ tìm kiếm.", task: "Kiểm tra mốc cắt dữ liệu (knowledge cutoff date) và cơ chế duyệt web thời gian thực của AI.", source: "Thông số kỹ thuật mô hình AI, tài liệu API chính thức của nhà phát triển.", verdict: "Sai", explain: "Mô hình ngôn ngữ có mốc đóng băng dữ liệu huấn luyện; trừ khi được tích hợp công cụ duyệt web (browsing tool), AI không tự biết sự kiện vừa xảy ra." },
  { group: "AI", topic: "Dịch thuật AI", title: "Thành ngữ tiếng Việt sang tiếng Anh", quote: "AI dịch câu thành ngữ 'Mẹ tròn con vuông' thành 'Round mother and square child' và khẳng định người bản xứ dùng câu này.", task: "Tra cứu cách diễn đạt tương đương trong từ điển thành ngữ đối chiếu Anh-Việt.", source: "Từ điển thành ngữ Anh-Việt, cách diễn đạt chuẩn: 'Safe and sound', 'Healthy birth'.", verdict: "Sai", explain: "AI đã dịch máy móc từng từ (word-by-word) mà không hiểu nghĩa ẩn dụ của thành ngữ văn hóa Việt Nam." },
  { group: "AI", topic: "Định kiến AI", title: "Hình ảnh nghề nghiệp và giới tính", quote: "AI khẳng định tất cả các lập trình viên giỏi trên thế giới đều phải là nam giới và y tá luôn là nữ.", task: "Kiểm tra lịch sử công nghệ và hiện tượng định kiến dữ liệu (algorithmic bias) trong AI.", source: "Lịch sử tin học thế giới, nghiên cứu về AI Fairness của UNESCO.", verdict: "Sai", explain: "AI phản ánh thiên kiến có trong dữ liệu huấn luyện lịch sử; năng lực chuyên môn không phụ thuộc vào giới tính." }
];
